### ISSUE TITLE
It was hung when run stressapptest app in vmlinux

### ISSUE THREAD

**Issue by Makebug** [SEL4PROJ/camkes-arm-vm-manifest#5]
i run stressapptest ( [Linker](https://github.com/stressapptest/stressapptest)) in the vmlinux that work on seL4 .
Exception occurred after a period of time ,the system was hung
![image](https://user-images.githubusercontent.com/16549608/121524166-9bb91500-ca29-11eb-95ca-57b1aa253e3e.png)
it was hung here and can not stop it with ctrl+c

After a long time , output the following information:
![image](https://user-images.githubusercontent.com/16549608/121524560-023e3300-ca2a-11eb-8904-9f78c632093b.png)

Have you have a similar problem? 
Not clear about this issue of the root cause, Is there a way to debug? 
Please give me some suggestions for

thanks!!

BR
Gordon

**Comment by kent-mcleod** [comment]
Are you able to provide more information about the hardware and app configuration you were running? And also how you ran stressapptest?

**Comment by lsf37** [comment]
Will close this since the repo will be archived. Please feel free to re-raise and continue the discussion on <https://github.com/seL4/camkes-vm-examples-manifest>
